# Generated by Django 3.1.4 on 2023-09-29 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_auto_20230928_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Известные женщины', 'verbose_name_plural': 'Известные женщины'},
        ),
    ]
